### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by dorianmariefr** [zombocom/dead_end#124]
```
retained memory by gem
-----------------------------------
   2643413  dead_end-3.1.1

allocated objects by location
-----------------------------------
    252404  /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19
    118590  /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:30

allocated objects by file
-----------------------------------
    372794  /Users/dorianmariefr/.rvm/gems/ruby-3.0.3/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb

allocated objects by gem
-----------------------------------
    372794  dead_end-3.1.1
```

and in case it might be useful:

```
allocated memory by class
-----------------------------------
  30325876  String
  15374176  File
   3715336  Class
   3533088  Hash
   2718504  Array
   2186776  MatchData
    825600  Proc
    630626  Regexp
    596920  Module
```

this gem is in my bundle because I run the derailed benchmarks

**Comment by dorianmariefr** [comment]
basically 40MB it seems like

**Comment by dorianmariefr** [comment]
oops forgot to put derailed_benchmarks in development group

**Comment by dorianmariefr** [comment]
hmmm even in development it is required by `bundle exec derailed bundle:objects`

**Comment by schneems** [comment]
## Memory profiler

That line in dead end isn't doing anything, it's forwarding to your original require call https://github.com/zombocom/dead_end/blob/10232e47fbf4c1372f92b3057cbdc9876f771ca9/lib/dead_end/core_ext.rb#L19. You'll have the same issue if you put bootstrap (or any other gem that aliases`require`).

Basically whatever file you're loading is actually allocating all that memory. Dead end is getting the blame because it's in the middle.

## Dead end monkeypatching 

The reason dead end needs that monkeypatch is SyntaxError cannot be monkeypatched. There's a plan to move SyntaxError to be patchable via Ruby core, then we could hook into the exception directly instead of this round-about method which causes confusing results like this sometimes.

## Getting require memory with dead_end

If the memory is showing up at boot/require time then it should show up with the other tasks: `bundle exec derailed bundle:mem` or `bundle exec derailed bundle:objects`. 

Fun fact, derailed uses the same trick to profile require memory (overwriting require) as dead end uses to catch syntax errors today.

**Comment by dorianmariefr** [comment]
ok makes sense thanks
